services:
  mysql:
    image: mysql:8.4
    container_name: wingstars-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '2001'
      MYSQL_DATABASE: wingstars
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../wingstar-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p2001"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: wingstars-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wingstars
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '2001'